<a href="https://colab.research.google.com/github/nishantkumar1308/Getting-Started-With-google-Colab/blob/main/Gettingnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [7]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a[0][2])

3


In [12]:
np.ones(2)


array([1., 1.])

In [13]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [16]:
 x=np.arange(4);
 print(x)

[0 1 2 3]


In [17]:
a=np.array([1,2,3,4,10,2,3,6]);
a.sort()
print(a)

[ 1  2  2  3  3  4  6 10]


In [24]:
a=np.array([9,4,5,6]);
b=np.array([5,6,7,3]);
x=np.concatenate((a,b))
print(x)




[9 4 5 6 5 6 7 3]


checking shape size and dimension of the ndarray

In [33]:
 a=np.array([[1,2],[3,4],[5,6]]);
 print(a.ndim)
 print(a.size)
 print(a.shape)

2
6
(3, 2)
